import { ReactNode } from 'react'
import './globals.css'
import { Rubik } from 'next/font/google'

const rubik = Rubik({ subsets: ['latin'], variable: '--font-rubik' })

export const metadata = {
  title: 'Frontend Mentor - IP address tracker',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} font-sans`}>{children}</body>
    </html>
  )
}
